# **Pandas**
___

In [2]:
# instalar las librerias para este jupyter
! pip install pandas
! pip install numpy

Requirement already satisfied: pandas in d:\anaconda3\envs\pruebas\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.21.0 in d:\anaconda3\envs\pruebas\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in d:\anaconda3\envs\pruebas\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\envs\pruebas\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in d:\anaconda3\envs\pruebas\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in d:\anaconda3\envs\pruebas\lib\site-packages (1.22.4)

In [3]:
# imports para trabajar con DataFrames
import pandas as pd
import numpy as np
import os

## DataFrame leyendo csv

In [4]:
# importar el data set desde csv
archivo = 'netflix_titles.csv'
carpeta = os.path.join(os.path.realpath('.'), 'data_sets', archivo)

In [5]:
# crear el DataFrame leyendo el archivo csv
netflix = pd.read_csv(carpeta)
netflix.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## DataFrame leyendo excel

In [6]:
# importar el data set desde excel
archivo = 'netflix_titles.csv'
hoja = "Hoja 1"
carpeta = os.path.join(os.path.realpath('.'), 'data_sets', archivo)

In [7]:
# crear el DataFrame leyendo el archivo excel
netflix = pd.read_excel(archivo, hoja)

## Exportar a csv

In [ ]:
# exportar con indices
netflix.to_csv('ruta_de_destino', encoding='utf-8')

# exportar sin indices
netflix.to_csv('ruta_de_destino', encoding='utf-8', index=False)

# con punto y coma
netflix.to_csv('ruta_de_destino', encoding='utf-8', set=';')

## Exportar a excel

In [ ]:
# exportar con indices
netflix.to_excel('ruta_de_destino', encoding='utf-8')

# exportar sin indices
netflix.to_excel('ruta_de_destino', encoding='utf-8', index=False)

## Conocer el DataFrame actual

In [8]:
# mostrar info del DataFrame
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [9]:
# para saber la cantidad de filas y columnas en ese orden
netflix.shape

(8807, 12)

In [10]:
# saber cuantas columnas hay en el DataFrame
netflix.columns.values

array(['show_id', 'type', 'title', 'director', 'cast', 'country',
       'date_added', 'release_year', 'rating', 'duration', 'listed_in',
       'description'], dtype=object)

In [11]:
# para saber los nombres de las columnas y a la derecha el tipo de dato guardado en la columna
netflix.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [12]:
# ultimas 5 lineas del DataFrame
netflix.tail(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [13]:
# seleccionar solo las columnas que necesitamos, sirve para eliminar la que no nos sirven
netflix2 = netflix[['type', 'title', 'country']]
netflix2.head(5)

      type                  title        country
0    Movie   Dick Johnson Is Dead  United States
1  TV Show          Blood & Water   South Africa
2  TV Show              Ganglands            NaN
3  TV Show  Jailbirds New Orleans            NaN
4  TV Show           Kota Factory          India

In [14]:
# para conocer las medidas de tendencia central y de dispercion de las columnas cuantitativas del DataFrame
netflix.describe()  # en este caso los años

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

## Manejo de valores NaN

In [15]:
# dropna para eliminar campos con NaN del DataFrame
netflix3 = netflix.dropna(axis=0, how='all')
# en el parametro axis= 0 si es fila; 1 si es columna;
# en el parametro how='all' si es para eliminar las filas o columnas que cumplan con la condicion
# en el parametro how='any' si es para eliminar todas las filas o columnas que cumplan con la condicion
netflix3.shape

(8807, 12)

In [16]:
# para saber cuantos son los valores NaN en cada columna especificada
netflix3['duration'].isnull().values.ravel().sum()
# pd.isnull(netflix3['duration']).values.ravel().sum()
# values devuelve los valores de la columna, me quedo con los que son null y con sum() los sumo

3

In [55]:
# para ver cuantas filas tienen NaN en cada columna
netflix3.isna().sum()

show_id             0
type                0
title               0
director         2634
cast              825
country           831
date_added         10
release_year        0
rating              4
duration            3
listed_in           0
description         0
nueva_columna       0
dtype: int64

In [52]:
# para quedarnos solo con los que sean NaN en la columna cast
los_nan = netflix['cast'].isnull()
los_nan

0        True
1       False
2       False
3        True
4       False
        ...
8802    False
8803     True
8804    False
8805    False
8806    False
Name: cast, Length: 8807, dtype: bool

In [18]:
# con fillna rellenar los valores NaN con un valor especificado en la columna seleccionada,
# en este caso, con la media (mean())
col = netflix3['release_year'].mean()
netflix3['release_year'].fillna(col, inplace=True)
netflix3.head(5)

# tambien en una sola columna en el mismo DataFrame
# netflix3['release_year'].fillna(80, inplace=True)

# tambien de la manera aplicandolo en todas las columnas
# netflix3.fillna(80, inplace=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [19]:
# para generar una nueva columna con datos calculados
netflix3['nueva_columna'] = col
netflix3.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,nueva_columna
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2014.180198
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2014.180198
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2014.180198
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2014.180198
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2014.180198

## Concatenar dos o mas DataFrames

In [20]:
# con iloc para seleccionar las filas que queremos
# los primeros 1:1 son las filas y la proxima 2:2 son las columnas dentro del iloc[]
# si se pone solo dos puntos (iloc[:, 1]) toma todas las filas de la columna 1
# si se pone solo dos puntos (iloc[1, :]) toma todas las columnas de la fila 1
# tambien se puede poner una lista con las filas o columnas que queremos
n1 = netflix3.iloc[7:12]
n2 = netflix3.iloc[0:5]

In [21]:
# para concatenar dos DataFrames
n3 = pd.concat([n1, n2])
n3

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,nueva_columna
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2014.180198
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2014.180198
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2014.180198
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B...",2014.180198
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ...",2014.180198
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2014.180198
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2014.180198
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2014.180198
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2014.180198
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2014.180198

## Concatenar dos o mas columnas en un DataFrame

In [22]:
# para este ejemplo separamos tres columnas en net1 y dos en net2
net1 = netflix3[['type', 'title', 'country']]
net2 = netflix3[['duration', 'nueva_columna']]

In [23]:
# concatenar las columnas seleccionadas, con axis en 1 para decirle que son las columnas a concatenar
net3 = pd.concat([net1, net2], axis=1)
net3

         type                  title        country   duration  nueva_columna
0       Movie   Dick Johnson Is Dead  United States     90 min    2014.180198
1     TV Show          Blood & Water   South Africa  2 Seasons    2014.180198
2     TV Show              Ganglands            NaN   1 Season    2014.180198
3     TV Show  Jailbirds New Orleans            NaN   1 Season    2014.180198
4     TV Show           Kota Factory          India  2 Seasons    2014.180198
...       ...                    ...            ...        ...            ...
8802    Movie                 Zodiac  United States    158 min    2014.180198
8803  TV Show            Zombie Dumb            NaN  2 Seasons    2014.180198
8804    Movie             Zombieland  United States     88 min    2014.180198
8805    Movie                   Zoom  United States     88 min    2014.180198
8806    Movie                 Zubaan          India    111 min    2014.180198

[8807 rows x 5 columns]

## Ordenar el DataFrame

In [24]:
netflix.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [25]:
# para ordenar la columna que queremos de manera ascendiente
# con el parametro ascending=False para ordenar de forma descendiente
netflix_2 = netflix.sort_values('country')
netflix_2.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
365,s366,Movie,Eyes of a Thief,Najwa Najjar,"Khaled Abol El Naga, Souad Massi, Suhail Hadda...",", France, Algeria","July 30, 2021",2014,TV-14,103 min,"Dramas, Independent Movies, International Movies","After a decade in prison, a Palestinian man wi..."
193,s194,TV Show,D.P.,NaN,"Jung Hae-in, Koo Kyo-hwan, Kim Sung-kyun, Son ...",", South Korea","August 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas",A young private’s assignment to capture army d...
6400,s6401,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...",Argentina,"January 20, 2017",2016,TV-MA,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
5001,s5002,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",Malena Pichot,Argentina,"March 2, 2018",2018,TV-MA,51 min,Stand-Up Comedy,An Argentine comedian espouses the values of f...
2894,s2895,TV Show,Puerta 7,NaN,"Dolores Fonzi, Esteban Lamothe, Carlos Belloso...",Argentina,"February 21, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A determined woman works to rid an Argentine s...

In [26]:
# con reset_index, reseteamos los indices desde el valor que se pase en "level" de manera ascendente
netflix_7 = netflix_2.reset_index(level=0).drop(columns=['index', 'show_id'])
netflix_7.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,Movie,Eyes of a Thief,Najwa Najjar,"Khaled Abol El Naga, Souad Massi, Suhail Hadda...",", France, Algeria","July 30, 2021",2014,TV-14,103 min,"Dramas, Independent Movies, International Movies","After a decade in prison, a Palestinian man wi..."
1,TV Show,D.P.,NaN,"Jung Hae-in, Koo Kyo-hwan, Kim Sung-kyun, Son ...",", South Korea","August 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas",A young private’s assignment to capture army d...
2,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...",Argentina,"January 20, 2017",2016,TV-MA,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
3,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",Malena Pichot,Argentina,"March 2, 2018",2018,TV-MA,51 min,Stand-Up Comedy,An Argentine comedian espouses the values of f...
4,TV Show,Puerta 7,NaN,"Dolores Fonzi, Esteban Lamothe, Carlos Belloso...",Argentina,"February 21, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A determined woman works to rid an Argentine s...

In [27]:
# cambiar de nombre a las columnas
netflix_2.rename(columns={'country': 'pais'}).head(5)

,show_id,type,title,director,cast,pais,date_added,release_year,rating,duration,listed_in,description
365,s366,Movie,Eyes of a Thief,Najwa Najjar,"Khaled Abol El Naga, Souad Massi, Suhail Hadda...",", France, Algeria","July 30, 2021",2014,TV-14,103 min,"Dramas, Independent Movies, International Movies","After a decade in prison, a Palestinian man wi..."
193,s194,TV Show,D.P.,NaN,"Jung Hae-in, Koo Kyo-hwan, Kim Sung-kyun, Son ...",", South Korea","August 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas",A young private’s assignment to capture army d...
6400,s6401,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...",Argentina,"January 20, 2017",2016,TV-MA,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
5001,s5002,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",Malena Pichot,Argentina,"March 2, 2018",2018,TV-MA,51 min,Stand-Up Comedy,An Argentine comedian espouses the values of f...
2894,s2895,TV Show,Puerta 7,NaN,"Dolores Fonzi, Esteban Lamothe, Carlos Belloso...",Argentina,"February 21, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A determined woman works to rid an Argentine s...

In [28]:
# para cambiar los indices de las filas
netflix_2.set_index('country', inplace=True)
netflix_2.head(5)

,show_id,type,title,director,cast,date_added,release_year,rating,duration,listed_in,description
country,,,,,,,,,,,
", France, Algeria",s366,Movie,Eyes of a Thief,Najwa Najjar,"Khaled Abol El Naga, Souad Massi, Suhail Hadda...","July 30, 2021",2014,TV-14,103 min,"Dramas, Independent Movies, International Movies","After a decade in prison, a Palestinian man wi..."
", South Korea",s194,TV Show,D.P.,NaN,"Jung Hae-in, Koo Kyo-hwan, Kim Sung-kyun, Son ...","August 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas",A young private’s assignment to capture army d...
Argentina,s6401,Movie,Caida del Cielo,Néstor Sánchez Sotelo,"Muriel Santa Ana, Peto Menahem, Héctor Díaz, S...","January 20, 2017",2016,TV-MA,78 min,"Comedies, International Movies, Romantic Movies",When Julia literally falls into Alejandro's ba...
Argentina,s5002,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",Malena Pichot,"March 2, 2018",2018,TV-MA,51 min,Stand-Up Comedy,An Argentine comedian espouses the values of f...
Argentina,s2895,TV Show,Puerta 7,NaN,"Dolores Fonzi, Esteban Lamothe, Carlos Belloso...","February 21, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A determined woman works to rid an Argentine s...

In [29]:
# ahora que cambiamos los indices de las filas por los paises, podemos hacer que muestre los
# que tienen indice como 'Argentina'
# y desp de la coma las columnas que queremos que se muestren
netflix_2.loc['Argentina',['type', 'title', 'director', 'release_year']].head(5)

,type,title,director,release_year
country,,,,
Argentina,Movie,Caida del Cielo,Néstor Sánchez Sotelo,2016
Argentina,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",2018
Argentina,TV Show,Puerta 7,NaN,2020
Argentina,TV Show,Edha,NaN,2018
Argentina,Movie,Daemonium,Pablo Parés,2015

In [30]:
# para ver desde tal fila hasta tal fila y tales columnas, lo mismo que se hace con filas se puede con columnas
netflix_2.loc['Argentina':'Mexico', ['type', 'title', 'director', 'release_year']]

,type,title,director,release_year
country,,,,
Argentina,Movie,Caida del Cielo,Néstor Sánchez Sotelo,2016
Argentina,Movie,Malena Pichot: Estupidez compleja,"Raúl Campos, Jan Suter",2018
Argentina,TV Show,Puerta 7,NaN,2020
Argentina,TV Show,Edha,NaN,2018
Argentina,Movie,Daemonium,Pablo Parés,2015
...,...,...,...,...
Mexico,Movie,Semana Santa,Alejandra Márquez Abella,2015
Mexico,Movie,The Perfect Dictatorship,Luis Estrada,2014
Mexico,Movie,Ricardo O'Farrill: Abrazo navideño,"Raúl Campos, Jan Suter",2016
Mexico,Movie,Mexicanos de Bronce,Julio Fernández Talamantes,2016
Mexico,Movie,Mutiny of the Worker Bees,Carlos Morett,2020

## Eliminar columnas

In [ ]:
# eliminar todas las filas con NaN
netflix.dropna()

In [31]:
eliminado = netflix.drop(columns=['duration', 'description'])
eliminado.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,Documentaries
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ..."

In [32]:
# elimina todas las lineas duplicadas
nuevo = netflix2.drop_duplicates()
nuevo

         type                  title        country
0       Movie   Dick Johnson Is Dead  United States
1     TV Show          Blood & Water   South Africa
2     TV Show              Ganglands            NaN
3     TV Show  Jailbirds New Orleans            NaN
4     TV Show           Kota Factory          India
...       ...                    ...            ...
8802    Movie                 Zodiac  United States
8803  TV Show            Zombie Dumb            NaN
8804    Movie             Zombieland  United States
8805    Movie                   Zoom  United States
8806    Movie                 Zubaan          India

[8807 rows x 3 columns]

## Seleccionar según algun criterio

In [33]:
# segun algun criterio numerico
netflix[netflix.release_year >= 2007].head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [34]:
# de manera aleatoria n = cantidad de filas que queremos que se muestren
netflix.sample(n=1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8047,s8048,Movie,Socha Na Tha,Imtiaz Ali,"Abhay Deol, Ayesha Takia, Apoorva Jha, Ayesha ...",India,"July 1, 2018",2005,TV-14,137 min,"Comedies, International Movies, Romantic Movies",An arranged marriage becomes a friendship for ...

In [47]:
for x in netflix.index:
    if netflix.loc[x, "release_year"] > 2020:
        netflix.loc[x, "release_year"] = 120
netflix.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",120,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",120,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",120,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",120,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## Calculo de mínimos y máximos

In [45]:
# mostrar los 5 valores mas altos de la columna seleccionada
netflix.nlargest(5, 'release_year')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...
34,s35,TV Show,Tayo and Little Wizards,NaN,"Dami Lee, Jason Lee, Bommie Catherine Han, Jen...",NaN,"September 17, 2021",2020,TV-Y7,1 Season,Kids' TV,Tayo speeds into an adventure when his friends...

In [44]:
# mostrar los 5 valores mas bajos de la columna seleccionada
netflix.nsmallest(5, 'release_year')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",120,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",120,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",120,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",120,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",120,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...

## Aplicar cambios a los registros de una columna

In [ ]:
netflix2['title'] = netflix2['title'].apply('una funcion definida o una lambda')

In [50]:
# al DataFrane le digo que en la columna title aplique la funcion lambda
# en este caso se queda con todas las filas que en la columna title empiece con "E"
netflix2[netflix2['title'].apply(lambda x: x.startswith('E'))]

,type,title,country
16,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,NaN
140,Movie,"El patrón, radiografía de un crimen","Argentina, Venezuela"
141,Movie,Extraction,"United States, United Kingdom, Canada"
195,Movie,EMI: Liya Hai To Chukana Padega,India
219,TV Show,EDENS ZERO,Japan
...,...,...,...
6724,TV Show,Extras,"United Kingdom, United States"
6725,Movie,Eyyvah Eyyvah,Turkey
6726,Movie,Eyyvah Eyyvah 2,Turkey
6727,Movie,Eyyvah Eyyvah 3,Turkey
6728,TV Show,Ezel,Turkey

## Filtros

In [ ]:
# seleccionar las columnas que empiezan con la palabra seguido de ^
netflix.filter(regex = '^una_columna').head(5)

In [ ]:
# para filtrar las columnas que terminan con la palabra antes del $
netflix.filter(regex = 'una_columna$').head()

## Sumar cantidades

In [ ]:
# para contabilizar el numero de registros que aparecen en la columna seleccionada
netflix['release_year'].value_counts()

## Manejo de fechas en pandas

In [ ]:
netflix['date_added'] = pd.to_datetime(netflix['date_added'])
netflix.head(5)

## Cambios de type

In [ ]:
# cambiasr el tipo de dato a una columna
netflix['release_year'] = netflix['release_year'].astype(float)

## Merge de DataFrames

In [ ]:
# para obtener un dataset con todos los registros de los dos datasets
pd.merge(netflix, netflix2, how='outer', left_index=True, right_index=True)

In [ ]:
# para obtener un dataset con los registros en comun de los dos datasets
pd.merge(netflix, netflix2, how='inner', left_index=True, right_index=True)

In [ ]:
# para obtener un dataset con los registros del dataset izquierdo y con la informacion de las columnas
# correspondiente del dataset derecho, lo mismo pero al reves con 'right' en el parametro how
pd.merge(netflix, netflix2, how='left', left_index=True, right_index=True)

In [ ]:
# para obtener un dataset en donde se ubican los registros exactos segun la lista de indices
# detecta cuales son los nombres o valores que se repiten en las columnas seleccionadas (inner)
pd.merge(netflix, netflix2, how='inner', on=['title', 'release_year'])

In [ ]:
resultado = pd.merge(df1, df1[['nombre', 'personal', 'equipos']], how="left")

In [ ]:
1655432283.6162822,db74505f-3fe3-476c-866d-872fea96a3b2,fin,NEO,80,Masculino,finalizada,,,Facil